name: Deploy to Production

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      #リポジトリの最新コードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      #AWS 認証情報の設定
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_IAM }}
          aws-region: ap-northeast-1

      #デプロイ用のパッケージを作成しS3にアップロード
      - name: Package and Push Deployment Revision
        run: |
          aws deploy push \
            --application-name interview-management \
            --s3-location "s3://my-interview-management/production-interview-management.zip" \
            --description "Deployment revision pushed from GitHub Actions"

      #CodeDeployを利用してデプロイをトリガー
      - name: Trigger Deployment via CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name interview-management \
            --deployment-group-name aws-code-deploy-group \
            --s3-location bucket=my-interview-management,key=production-interview-management.zip,bundleType=zip \
            --description "Deployment triggered from GitHub Actions"
