name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      #リポジトリの最新コードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      #AWS 認証情報の設定
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_IAM }}
          aws-region: ap-northeast-1

      #PHPのセットアップ
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      #PHPの依存関係をComposerでインストール
      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      #Nodeのセットアップ
      - name: Setup Node version-20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      #npminstallとビルド
      - name: Clean up node_modules and package-lock.json
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install Node dependencies and build assets
        run: |
            npm install
            npm run build

      #デプロイ用のパッケージを作成しS3にアップロード
      - name: Package and Push Deployment Revision
        run: |
          aws deploy push \
            --application-name interview-management \
            --s3-location "s3://my-interview-management/production-interview-management.zip" \
            --description "Deployment revision pushed from GitHub Actions"

      #CodeDeployを利用してデプロイをトリガー
      - name: Trigger Deployment via CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name interview-management \
            --deployment-group-name aws-code-deploy-group \
            --s3-location bucket=my-interview-management,key=production-package.zip,bundleType=zip \
            --description "Deployment triggered from GitHub Actions"
